server:
  port: 8083
  servlet:
    context-path: /api/credits
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ntt-ms-credits
    username: root
    password: 123456
    driver: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mvc:
    path-match:
      matching-strategy: ant_path_matcher

  application:
    name: credits-service

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka