server:
    port: 8083
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/ntt-ms-credits
        username: root
        password: 123456
        driver: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect