server:
  port: 8084

spring:
  data:
    mongodb: urimongodb\://localhost\:27017/mongo
    auto-index-creation: true
    database: db_transaction

  application:
    name: transactions-service

  mvc:
    path-match:
      matching-strategy: ant-path-matcher

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka